### PR TITLE
Note that `assert()` should be activated in CI

### PR DESCRIPTION
**Pull request by Slamdunk**
Ping @boesing

### CODE REVIEW

**Comment by boesing** [comment]
I dont know where you checked the default but it is definitely `1` by default and has to be actively disabled:

https://www.php.net/manual/en/function.assert.php

**Comment by Slamdunk** [comment]
As pointed in the issue, `laminas-continuous-integration-action` uses Ondřej Surý repositories, which pack PHP with the `php.ini-production` ini of `php-src`, which has `zend.assertion=-1`: https://github.com/php/php-src/blob/724230d9a4fc35eaf5b96d22f86927400233d02f/php.ini-production#L1579

**Comment by boesing** [comment]
Mh, I probably missed that. Which issue? 😅
Imho, this should be an issue in the container action rather than here. 

@weierophinney was there a specific background on why we chose production ini?

**Comment by Slamdunk** [comment]
The issue is linked in the first line of this PR: https://github.com/laminas/technical-steering-committee/pull/87/files#diff-3244d5bc99e4eebab67deabd8eaf9029a1d36e7aecbec33cdc6d27c16c449d9aR37

>  Imho, this should be an issue in the container action rather than here.

Indeed, this PR is just a reminder that an action had to be taken if `assert()` are going to be used

> @weierophinney was there a specific background on why we chose production ini?

I guess no one has ever "chose" it, it is just distributed as is and since the diff from the two inis are quite few, no one ever noticed

**Comment by Slamdunk** [comment]
I don't know where the sources are, but `deb` files tell this story:

https://packages.sury.org/php/pool/main/p/php8.0/php8.0-cli_8.0.5-2%2B0~20210503.19%2Bdebian11~1.gbp3e4ad0_amd64.deb


```sh
#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
    for binary in php phar phar.phar; do
        update-alternatives \
	    --install /usr/bin/${binary} ${binary} /usr/bin/${binary}8.0 80 \
	    --slave /usr/share/man/man1/${binary}.1.gz ${binary}.1.gz /usr/share/man/man1/${binary}8.0.1.gz
    done
fi

CONFDIR=/etc/php/8.0/cli/conf.d

if [ "$1" = "configure" ]; then
    phpini="/etc/php/8.0/cli/php.ini"

    if [ "cli" = "cli" ]; then
	ucf /usr/lib/php/8.0/php.ini-production.cli $phpini
    else
	ucf /usr/lib/php/8.0/php.ini-production $phpini
    fi
    ucfr php8.0-cli $phpini

    if [ -e /usr/lib/php/php-maintscript-helper ]; then
	. /usr/lib/php/php-maintscript-helper
	
	mods=$(phpquery -M -v 8.0)
	for mod in $mods; do
	    php_invoke enmod 8.0 cli $mod
	done
    fi

    if [ -n "$2" ] && dpkg --compare-versions "$2" lt "7.0.3-2~"; then
	rm -f /etc/php/8.0/cli/conf.d/20-opcache.ini;
    fi	    
fi



exit 0
```

In `/DEBIAN/postint`, and as you can see `production` ini is used.

**Comment by boesing** [comment]
`assert` is already being used in some cases. Ive seen at least a few PRS tho.

Sorry, I did not read the diff yet... 😅 
Just that  title tho...

**Comment by weierophinney** [comment]
> @weierophinney was there a specific background on why we chose production ini?

Nope. I simply didn't change from the default.

**Review by boesing — APPROVED** [review]

**Pull request merged**
