### PR TITLE
Provide status update on communicating status to users

### PR DESCRIPTION
**Pull request by visto9259**
### Description

Just requesting a status update for the actions of the March 4 TSC meeting on providing a status dashboard.

### CODE REVIEW

**Comment by froschdesign** [comment]
@visto9259 
The work is not yet completed. The custom properties in the repositories are created but not yet assigned values:

maintenance-mode

A working group still needs to be found to extend the readme files and to create the overview.
(I already have an idea for the overview.)

**Comment by visto9259** [comment]
Thanks for the update @froschdesign 

I did an overview page for LM-Commons based on a custom property on each repo.  I used shields.io to retrieve the custom property and turn it in a badge. Nothing fancy.

If I can be of assistance, let me know.

**Comment by boesing** [comment]
I wonder why there has to be a dedicated file. At least in the example I've detected in the TSC meeting required a file in each repository.
Having each repository updated via API (without an actual commit) would be a no brainer but that won't provide the current status within the repository itself (as we need `README.md` patch).

Sad that github does not support in an integrated way. :/
But I'd prefer having an overview over having to check every component, tho I do not have a strong need for the `README` change.

**Comment by froschdesign** [comment]
> But I'd prefer having an overview over having to check every component, tho I do not have a strong need for the `README` change.

This simplifies the entire process if we do not also try to modify the `Readme` files in the first step.

[Astro](https://astro.build) and a few simple scripts can help. Here is a test I did for the overview pages - as a replacement for [the current solution](https://github.com/laminas/laminas.github.io): 

- https://github.com/froschdesign/laminas-docs
- https://froschdesign.github.io/laminas-docs/

Adding the status dashboard would also be no problem.

**Comment by weierophinney** [comment]
I'm not going to merge this as @froschdesign has been providing updates here in the pull request.

**Pull request closed without merging**
