### PR TITLE
Discuss composer.json linting job

### PR DESCRIPTION
**Pull request by Slamdunk**

### CODE REVIEW

**Comment by weierophinney** [comment]
It's actually implicitly done in laminas-ci-matrix; if the composer.json is not parseable, you should get an error immediately from that job.

If that's not the case, I'd argue to just open an issue or PR against that repo, as being able to parse the composer.json is required for that action.

**Comment by Slamdunk** [comment]
The tools listed in https://github.com/laminas/laminas-ci-matrix-action/issues/22 do much more than just checking JSON validity.

I used the word linting because I couldn't find any better

**Comment by weierophinney** [comment]
I'm going to close this in favor of laminas/laminas-ci-matrix-action#22 - there's no need to discuss this in the TSC, as it's about the featureset of the tooling, which was designed for us to expand as we identify more needs.

**Comment by Slamdunk** [comment]
I have to say, I struggle to understand what must be discussed and what not.

So can I just create a PR that does what the issue suggests, without risking it to be dismissed as "TSC don't accept that" ?

**Pull request closed without merging**
