### PR TITLE
Removal of DCO: useless, painful, irrespectful of everyone's time and efforts

### PR DESCRIPTION
**Pull request by Ocramius**

### CODE REVIEW

**Comment by Ocramius** [comment]
The irony: 
Selection_569

**Comment by weierophinney** [comment]
This is a non-starter if we want to be under the Linux Foundation.

As I've commented elsewhere, it's easy to accomplish _in the commit message_ even when doing edits in the GitHub UI, by adding the following text:

```text
Signed-Off-By: {name}<email>
```

I _know_ it's inconvenient. But the point is _to protect the project from IP liability_.

**Comment by Ocramius** [comment]
Discussed briefly in chat, but this also precludes people that wish to stay anonymous from contributing anything to @laminas in first place, and that's huge.

I'll think more about it, but overall, I'd test the limits of this legal system, potentially pushing responsibility on myself as a maintainer: when I press "merge", I vouch for the author of the PR, regardless of their full name and email address (easily cheated system, as also discussed in chat).

Overall, it seems like no "official" position is possible from @laminas, if @laminas wants to stay under the Linux Foundation, but as a volunteering maintainer in this organization, I will likely act under my good faith, and deem DCO only required when major features are introduced, I suppose (basically considering almost everything under "Obvious Fix Policy").

**Comment by Maks3w** [comment]
I understand the needs. But once you notice the signed-off is missing then you need to redo the work (Chances abandon and throw away the contribution)

I've looking for some DCO / CLA alternatives and the following one looks like a nice approach to me.

image

https://github.com/cla-assistant/github-action

You can fix the CLA thing as a comment. Even for me is more clear what I'm doing (note the GitHub PR template is a bunch of lines in a small text area which you (may) quickly scroll down)

The handicap is for each signature it creates a commit in the repo.

It's just an idea

**Comment by weierophinney** [comment]
@Maks3w I've put in a query to our LF legal rep to see if that might be an option; thanks for linking to it!

**Comment by boesing** [comment]
home-assistant needs a registration on a website which passes DCO afterwards even without signing the commit afair.
Not sure what they're using but that might be an option aswell as I would prefer not having to comment on each PR when DCO is missing.

**Comment by Maks3w** [comment]
> home-assistant needs a registration on a website which passes DCO afterwards even without signing the commit afair.
> Not sure what they're using but that might be an option aswell as I would prefer not having to comment on each PR when DCO is missing.

If you are talking about `home-assistant.io`, as far as I see they are using a custom made [Github OAuth App](https://github.com/login/oauth/authorize?client_id=44151bab2be25f885aa7&response_type=code&scope=user%3Aemail&redirect_uri=https%3A%2F%2Fhome-assistant.io%2Fdevelopers%2Fcla_sign%2F) hosted in a custom server.

**Comment by weierophinney** [comment]
I've had a reply from the LF, and it turns out that the DCO bot we use... will accept a comment in the form of:

```text
Signed-Off-By: {fullname}<email>
```

or just:

```text
Signed-Off-By: {email}
```

The only stipulation is that the email needs to be the one used to send the commit; if you have chosen to keep your email private in GitHub, you need to use the noreply one associated with the commit you made.

As such, we can  have canned responses and/or a bot that comments when a DCO is needed with verbiage such as the above, and not require the contributors to muck about with rebase/sign-off.

**Comment by boesing** [comment]
> > home-assistant needs a registration on a website which passes DCO afterwards even without signing the commit afair.
> > Not sure what they're using but that might be an option aswell as I would prefer not having to comment on each PR when DCO is missing.
> 
> If you are talking about `home-assistant.io`, as far as I see they are using a custom made [Github OAuth App](https://github.com/login/oauth/authorize?client_id=44151bab2be25f885aa7&response_type=code&scope=user%3Aemail&redirect_uri=https%3A%2F%2Fhome-assistant.io%2Fdevelopers%2Fcla_sign%2F) hosted in a custom server.

Yep. I like that as you only have to provide it once. 🤷🏼‍♂️

**Pull request merged**
